'use strict';

const TOKENS = Object.freeze({
  EnvConfig: 'EnvConfig',
  DiscordConfig: 'DiscordConfig',
  DbConfig: 'DbConfig',
  RedisConfig: 'RedisConfig',
  Logger: 'Logger',
  ErrorMapper: 'ErrorMapper',
  LifecycleBootstrap: 'LifecycleBootstrap',
  DiscordClient: 'DiscordClient',
  EventRouter: 'EventRouter',
  InteractionRouter: 'InteractionRouter',
  InteractionMapper: 'InteractionMapper',
  InteractionResponder: 'InteractionResponder',
  CacheClient: 'CacheClient',
  PubClient: 'PubClient',
  SubClient: 'SubClient',
  RateLimitClient: 'RateLimitClient',
  QueueClient: 'QueueClient',
  RedisCacheBaseClient: 'RedisCacheBaseClient',
  RedisPubBaseClient: 'RedisPubBaseClient',
  RedisSubBaseClient: 'RedisSubBaseClient',
  RedisQueueBaseClient: 'RedisQueueBaseClient',
  RedisRateLimitBaseClient: 'RedisRateLimitBaseClient',
  CircuitBreakerRedis: 'CircuitBreakerRedis',
  CircuitBreakerDb: 'CircuitBreakerDb',
  DbPool: 'DbPool',
  TransactionManager: 'TransactionManager',
  L1Cache: 'L1Cache',
  CacheService: 'CacheService',
  QueueService: 'QueueService',
  RateLimitService: 'RateLimitService',
  PubSubService: 'PubSubService',
  PingService: 'PingService',
  ProfileService: 'ProfileService',
  ModerationService: 'ModerationService',
  PingController: 'PingController',
  ProfileController: 'ProfileController',
  ModerationController: 'ModerationController',
  InteractionOrchestrator: 'InteractionOrchestrator',
  UserRepository: 'UserRepository',
  GuildRepository: 'GuildRepository',
  WarningRepository: 'WarningRepository',
  UserCacheRepository: 'UserCacheRepository',
  WarningCacheRepository: 'WarningCacheRepository',
  Publisher: 'Publisher',
  CacheInvalidationSubscriber: 'CacheInvalidationSubscriber',
  ModerationConsumer: 'ModerationConsumer',
  RetryConsumer: 'RetryConsumer',
  DeadLetterWorker: 'DeadLetterWorker',
  MiddlewarePipeline: 'MiddlewarePipeline',
  ControllerRegistry: 'ControllerRegistry'
});

module.exports = { TOKENS };
